alias: Watchy Calendar Agenda
description: ""
triggers:
  - entity_id:
      - switch.watchy_56ae04_connected
    to: "on"
    trigger: state
conditions: []
actions:
  - response_variable: agenda
    metadata: {}
    target:
      entity_id:
        - calendar.main
        - calendar.birthdays
    action: calendar.get_events
    data_template:
      start_date_time: '{{ today_at("00:00:00") }}'
      end_date_time: '{{ today_at("23:59:59") }}'
  - alias: Parse data
    variables:
      simplified: |
        [
          {% for i in (agenda['calendar.main'].events + agenda['calendar.birthdays'].events) | sort(attribute="start") %}
            {% set start = as_datetime(i.start) %}
            {% set end = as_datetime(i.end) %}
            {% if start.day == now().day %}
              {{ [(start.hour * 60 + start.minute), (end.hour * 60 + end.minute) if end.day == now().day else (24 * 60), (i.summary | trim)] | to_json }},
            {% endif %}
          {% endfor %}
        ]
  - action: persistent_notification.create
    enabled: false
    data_template:
      message: |
        {{ simplified | to_json }}
  - data_template:
      agenda_json: "{{ simplified | to_json }}"
    action: esphome.watchy_56ae04_set_agenda
mode: single
